### ISSUE TITLE
Large jump in bundle size as of v1.1.0

### ISSUE THREAD

**Issue by probablyup** [auth0/auth0-react#176] opened 2020-12-17 19:15 UTC
### Describe the problem

> Provide a clear and concise description of the issue

Looking at bundlephobia, there was a substantial increase in bundled size for this library as of v1.1.0: https://bundlephobia.com/result?p=@auth0/auth0-react@1.2.0

I don't see anything in the changelog that would obviously support this bloat, so perhaps it was unintentional and crept in?

**Comment by frederikprijck** [comment] 2020-12-18 08:29
Hi, thanks for raising this.
Auth0-React is using Auth0-SPA-JS that had an increase in bundle size which was reverted, see https://github.com/auth0/auth0-spa-js/issues/608.

Chances are that the released React version is not using the patched SPA-JS that reduces the bundle size again.
We will investigate and see if that's the case.

**Comment by frederikprijck** [comment] 2021-01-11 10:25
It looks like the above mentioned reverted increase is properly reflected in the React SDK. However, the SPA-JS SDK has grown in size as, over time. As this is the main dependency of the React SDK, so did the Auth0-React SDK. 

We are aware of some unnecessary kilobytes in the SPA-JS-SDK, mainly due to polyfills and we are considering reworking the polyfills in a next major version of SPA JS. There is no timeline for this major release yet, but it is a known improvement that we are tracking internally.

As this is expected behavior, from the React SDK perspective, I am going to close this issue.

**Closed by frederikprijck** 2021-01-11 10:25 UTC
Labels: needs investigation
