### ISSUE TITLE
Add Support to Instantiate the Client Outside And Pass as a Prop (mainly for Redux middleware)

### ISSUE THREAD

**Issue by JANA-itsaishvili** [auth0/auth0-react#737] opened 2024-02-16 00:39 UTC
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

With RTK Query, Redux is a fully fledged state machine that can now handle HTTP requests. We use the api slice to communicate with our backend, and we pass the bearer token in a single place, in the middleware. To make this work, we are monkeypatching the `getTokenSilently` and calling it inside the middleware because the method is exposed as a `useCallback` hook only via `useAuth0`.

Basically we need access to some of the methods provided by the instantiation of Auth0Client outside of React. It's not hard.

### Describe the ideal solution

Looking at your code, you can give user the option to instantiate the client outside of the component/context and pass it as a prop. This way we can instantiate the Auth0Client in a static file, export it, passit to Auth0Provider and it will do what it is currently doing. Since your callbacks are referncing the client, nothing really needs to change. Except now you can also receive the client from outside, as a prop.

### Alternatives and current workarounds

I'm currently working on reimplementing what you already have by creating a context and exposing the client via the provider, along with some specific callbacks for our needs.

### Additional context

Looks like you've added some convenience props like `onRedirectCallback` that seems to have a slightly different signature from `openUrl`, so if the user passes the client that prop needs to be adjusted or disabled.

**Comment by frederikprijck** [comment] 2024-02-16 08:04
Closing as duplicate of https://github.com/auth0/auth0-react/issues/687.

For reasons, see:
- https://github.com/auth0/auth0-react/issues/687#issuecomment-1849621195
- https://github.com/auth0/auth0-react/pull/278#issuecomment-922846301

**Closed by frederikprijck** 2024-02-16 08:04 UTC
