### ISSUE TITLE
isAuthenticated always returning false

### ISSUE THREAD

**Issue by grug** [auth0/auth0-react#322] opened 2022-01-19 16:33 UTC
### Describe the problem

When following the [sample code](https://auth0.com/docs/quickstart/spa/react/01-login) the `isAuthenticated` flag is always returning false, even after login.

Any guidance here would be much appreciated as I'm scratching my head over this one.

### What was the expected behaviour?

When a user has successfully logged in, that the `isAuthenticated` flag is set to true.

### Reproduction

I have created a minimal repository here: https://github.com/grug/auth0-bug-reproduction

1. Clone the repo
2. Run `yarn install`
3. In the Auth0Provider, substitute your own client id and domain
4. Run `yarn start`
5. Hit the login button
6. Confirm redirect back into app
7. Observe that `isAuthenticated` is false

### Environment

- **Version of `auth0-react` used:** 1.9.0
- **Which browsers have you tested in?** Chrome/Firefox
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by frederikprijck** [comment] 2022-01-24 12:35
Hi,

It looks like you are using the `useAuth0` hook outside of the `Auth0Provider`:

```
const App = () => {
  const { isAuthenticated } = useAuth0();

  console.log("isAuthenticated", isAuthenticated);

  return (
    <Router>
      <Auth0ProviderWithHistory>
        ...
      </Auth0ProviderWithHistory>
    </Router>
  );
};
```
That is not something you want to be doing, instead ensure the useAuth0 is only called in children of the `Auth0Provider`. I opened a PR that changes this in your sample: https://github.com/grug/auth0-bug-reproduction/pull/1

Using the changes from that PR, I get the following output in the console:

![image](https://user-images.githubusercontent.com/2146903/150783860-64859489-091a-4d5d-9bec-156745bf4e87.png)

Closing as it looks like it should work now, happy to reopen if needed.

**Closed by frederikprijck** 2022-01-24 12:35 UTC

**Comment by grug** [comment] 2022-01-24 13:05
Oh lord that's embarrassing 😂 

Good catch - how silly! 

As a side note - would you be happy accepting a PR from me to add a warning when the hook is used outside of the context (it's not a big PR and would be cool to contribute to your library)?

**Comment by frederikprijck** [comment] 2022-01-24 13:09
Haha no worries! 😝 

We always appreciate PRs that help other people integrate our SDKs as seamlessly as possible.
Let me pull in @adamjmcgrath to see what he thinks about a change like this!

**Comment by grug** [comment] 2022-01-24 13:11
Excellent! As a point of reference, Kent Dodds recommends the throwing-when-not-used-within-the-provider-context pattern here: https://kentcdodds.com/blog/how-to-use-react-context-effectively

**Comment by adamjmcgrath** [comment] 2022-01-26 10:56
> Let me pull in @adamjmcgrath to see what he thinks about a change like this!

sgtm 👍

**Comment by grug** [comment] 2022-01-26 11:04
Excellent - I'll hopefully get a PR up soon :)
