### ISSUE TITLE
Invalid State on Protected Route with query parameters

### ISSUE THREAD

**Issue by lvillacin** [auth0/auth0-react#204] opened 2021-02-23 21:06 UTC
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I am implementing an OAUTH2.0 process outside of Auth0 because it is just to connect a Slack Workspace and I don't want my users to be able to login using their slack. This functionality is hidden behind a protected route so users can only connect their Slack account after logging in with Auth0. 

My problem is that after the user authorizes my app and slack redirects to `mydomain.com/slackcode=SLACKCODE&state=SLACKSTATE` my app gets stuck in the unauthenticated state. When I try to open `mydomain.com/slack` I am automatically authenticated again like normal. It seems that I get an Invalid State error when this happens.

### What was the expected behavior?

When I slack redirects to `mydomain.com/slack?code=SLACKCODE&state=SLACKSTATE` i want my users to be authenticated right away just like normal.

### Reference

I seem to have the same problem as this person from stackoverflow but there were no solutions available aside from not using query parameters (which do work) but I cannot do that because the OAUTH2 process uses query parameters.

https://stackoverflow.com/questions/62038511/invalid-state-when-i-come-back-on-a-auth0-private-route-on-a-react-application

### Environment

> Please provide the following:

- **Version of `auth0-react` used: ^1.2.0**
- **Which browsers have you tested in? Chrome**
- **Which framework are you using, if applicable (Angular, React, etc): React**
- **Other modules/plugins/libraries that might be involved: none**

**Comment by adamjmcgrath** [comment] 2021-02-24 08:35
Hi @lvillacin - thanks for raising this

It sounds like this SDK is clashing with another OAuth provider. This SDK is designed to check for `code` and `state` query params when the page is loaded and attempt to login with them. But because they are meant for Slack rather than Auth0, the login fails.

We have an option to handle these use cases called `skipRedirectCallback`, which will essentially tell the Auth0 React SDK to ignore those query parameters under some cases, eg to ignore these when the pathname is `/slack`. See https://auth0.github.io/auth0-react/interfaces/auth0_provider.auth0provideroptions.html#skipredirectcallback

**Comment by lvillacin** [comment] 2021-02-25 12:51
Thank you very much @adamjmcgrath! This does work however, I found that `skipRedirectCallback` seems to get ignored when im developing on `localhost:3000` so whilst the user now gets signed in, I still get an `Invalid State` error. **It was only after I deployed it that things worked as expected.** Before you close this issue, may I ask if this is expected behavior and should be added to the docs or is this a bug? Thank you!

**Comment by adamjmcgrath** [comment] 2021-02-25 14:54
Hi @lvillacin - `skipRedirectCallback` should work the same on `localhost`

Can you share a link to some code for how you've implemented `skipRedirectCallback` or a link to the app (the code or the running application)?

**Comment by lvillacin** [comment] 2021-02-25 15:12
In index.js

**Comment by lvillacin** [comment] 2021-02-25 15:21
In `index.js`

```
ReactDOM.render(
  <React.StrictMode>
    <Auth0Provider
      domain={auth0Domain}
      clientId={auth0ClientId}
      redirectUri={window.location.origin}
      skipRedirectCallback={window.location.pathname === '/slack'}
    >
      <App />
    </Auth0Provider>

  </React.StrictMode>,
  document.getElementById('root')
);
```
In `app.js`: `/` and `/slack` routes lead to the same component. I just have some logic to handle slack's OAUTH.
```
const App = () => {

  const { isAuthenticated, getAccessTokenSilently, getAccessTokenWithPopup, user } = useAuth0()

  const checkUser = async() => {
    //some code that uses getAccessTokenSilently if deployed or getAccessTokenWithPopup if localhost
  }

  useEffect(() => {
    if (isAuthenticated) {
      checkUser()
    }
  }, [isAuthenticated])

  if (isAuthenticated) {
    return (
      <Router>
        <Switch>
          <Route path="/slack" component={UserPage}/>
          <Route path="/" component={UserPage}/>
        </Switch>
      </Router>
    )
  } else {
    return (
      <LoginPage/>
    )
  }


}
```

I use `getAccessTokenSilently()` and  `getAccessTokenWithPopup()` to retrieve Auth0 tokens and pass them to my REST API backend which is lambda/api gateway with jwt authorizer.

Could `getAccessTokenWithPopup` cause this error on localhost? Thank you very much @adamjmcgrath

**Comment by adamjmcgrath** [comment] 2021-02-25 17:21
@lvillacin - thanks for sharing this code

> `skipRedirectCallback={window.location.pathname === '/slack'}`

This looks good 👍 

> I use getAccessTokenSilently() and getAccessTokenWithPopup() to retrieve Auth0 tokens and pass them to my REST API backend which is lambda/api gateway with jwt authorizer.

Yep - sounds good 👍 - although you only need to call `getAccessTokenWithPopup` on localhost when `getAccessTokenSilently` fails with `consent_required` - it might be annoying to have the popup launch everytime you refresh the page in development.

> Could getAccessTokenWithPopup cause this error on localhost? Thank you very much @adamjmcgrath

I'm not able to reproduce this, adding this snippet to the [playground app](https://github.com/auth0/auth0-react/blob/master/static/index.html)

```js
useEffect(() => {
  if (isAuthenticated) {
    getAccessTokenWithPopup()
  }
}, [isAuthenticated]);
```

Can you update the [playground app](https://github.com/auth0/auth0-react/blob/master/static/index.html) to reproduce the issue their?

**Comment by adamjmcgrath** [comment] 2021-03-09 12:29
Hi @lvillacin - closing this issue due to innactivity

Feel free to ping me if you'd like me to reopen it

**Closed by adamjmcgrath** 2021-03-09 12:29 UTC
Labels: question
