### ISSUE TITLE
Login required on mobile browser 

### ISSUE THREAD

**Issue by aleguern** [auth0/auth0-react#520] opened 2023-03-07 12:58 UTC
Hello,

I’m getting an error while using the SDK with react only on mobile browser.

I’m calling loginWithRedirect and then getAccessTokenSilently and it throws the error “Login required”.

My configuration is the following: (I tried removing, scope, userefreshtokens or cacheLocation but it does not fix it)

```
<Auth0Provider
      domain="DOMAIN"
      clientId="CLIENT_ID"
      authorizationParams={{
        audience: "AUDIENCE",
        redirect_uri: window.location.origin + "/login",
        cacheLocation: "localstorage",
        useRefreshTokens: true,
        scope: "read:current_user",
      }}
    >
```

```
"@auth0/auth0-react": "^2.0.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.8.1"
```
What should I do ? (No answers found on other topics)

**Comment by frederikprijck** [comment] 2023-03-07 18:09
Thanks for reaching out.

Can you elaborate on which browser is involved? 

Can you verify the issue is reproducible using our [Sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01)?

**Comment by aleguern** [comment] 2023-03-10 11:33
After many hours of debugging, I found that my providers where not in the right order, [reference](https://developer.auth0.com/resources/guides/spa/react/basic-authentication#configure-a-react-authentication-provider)

I did 
```
<Auth0Provider>
  <BrowserRouter>
    <App />
  </BrowserRouter>
</Auth0Provider>
```

instead of 

```
<BrowserRouter>
  <Auth0Provider>
    <App />
  </Auth0Provider>
</BrowserRouter>
```

**Comment by adamjmcgrath** [comment] 2023-03-14 11:03
Thanks for sharing your resolution @aleguern, am closing

**Closed by adamjmcgrath** 2023-03-14 11:03 UTC
Labels: more info needed
