### ISSUE TITLE
When MFA + rotating refresh tokens enabled, `getAccessTokenSilently` fails with `Error: MFA Required`

### ISSUE THREAD

**Issue by zachgoll** [auth0/auth0-react#501] opened 2023-02-12 16:46 UTC
### Describe the problem

When a user has MFA enabled, the `getAccessTokenSilently` throws an `Error: MFA Required` error when attempting to use the refresh token against the `/oauth/token` endpoint after the JWT expires ([see docs here](https://auth0.com/docs/secure/tokens/access-tokens#access-token-lifetime))

### What was the expected behavior?

I would expect that refresh tokens would still work with MFA enabled.  I _probably_ have something configured incorrectly that is causing this refresh failure, but I'm unsure where to look, and the help forums don't seem to cover this case ([here](https://community.auth0.com/t/failed-silent-auth-multifactor-authentication-required-error/46923/3), [here](https://community.auth0.com/t/problem-with-mfa-error-login-required/49408/2), and [here](https://community.auth0.com/t/silent-auth-fails-due-to-mfa-switched-on/8347/4)).  Hoping this issue can also act as some documentation for those stumbling on it in the future!

Currently, I'm using the following logic to work around this (as [suggested in the docs](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#call-an-api)) and recover from the error (the handler shown below is my interpretation of [this recommendation](https://github.com/auth0/auth0-react/issues/470#issuecomment-1385393467)).

I have also set the `allowRememberBrowser: true` as [documented here](https://auth0.com/docs/secure/multi-factor-authentication/customize-mfa#customize-mfa-for-select-users), which if checked by the user, will skip the MFA prompt after error is recovered from.  This solution works fine, but seems pretty complex to me (and not sure if filtering these error codes is stable)?  Is there a better way documented somewhere?  Or is this correct?

```ts
// Anywhere `getAccessTokenSilently` is called, catch errors and redirect to login
try {
   const token = await getAccessTokenSilently()
   // Do something with token
} catch (err) {
    const authErr =
        err && typeof err === 'object' && 'error' in err && typeof err.error === 'string'
            ? err.error
            : null
    const isRecoverable = authErr
        ? [
                'mfa_required',
                'consent_required',
                'interaction_required',
                'login_required',
            ].includes(authErr)
        : false

    if (isRecoverable) {
        await loginWithRedirect({ appState: { returnTo: window.location.pathname } })
    } else {
        Sentry.captureException(err)
    }
}
```

### Reproduction

I have reproduced this with a minimal repository linked below.  The repository has a `README` with instructions on how to reproduce the error.

https://github.com/zachgoll/auth0-react-mfa-refresh-bug-reproduction

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** - `2.0.0`
- **Which browsers have you tested in?** - Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** Next.js in SPA mode
- **Other modules/plugins/libraries that might be involved:** `express-jwt`, `jwks`

**Comment by frederikprijck** [comment] 2023-02-21 11:01
Hello,

Having looked into it it seems to be expected that Auth0 doesn't allow exchanging refresh tokens when you set `allowRememberBrowser` to false, which looks like [what you are doing](https://github.com/zachgoll/auth0-react-mfa-refresh-bug-reproduction/blob/main/auth0/rules/mfa.js).

There isn't much we can do from the SDK side, but if product feedback is always appreciated through https://auth0.com/feedback

Closing, as there isn't anything to action from our SDK.

**Closed by frederikprijck** 2023-02-21 11:01 UTC
