### ISSUE TITLE
WithAuthenticationRequiredOptions doesn't pass `appState`

### ISSUE THREAD

**Issue by adenta** [auth0/auth0-react#118] opened 2020-09-22 07:01 UTC
### Describe the problem

I modified the `<PrivateRoute/>` component to take `appState` and it does not work.

### What was the expected behavior?

I would expect the `extra_params` of the old lock-based Auth0 page to be populated. This is what happens when passing data to `loginWithRedirect`. 

### Reproduction

1. modify private route (see below)
2. log in
3. `console.log` the config being rendered on the universal login page.
4. notice issue

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

```
const PrivateRoute = ({ component, ...args }) => (
  <Route
    component={withAuthenticationRequired(component, {
      onRedirecting: () => <Loading />,
      loginOptions: { appState:{foo:'bar'} },
      ...Auth0Options,
    })}
    {...args}
  />
);

export default PrivateRoute;
```

### Environment

> Please provide the following:

- **Version of `auth0-react` latest
- **Which browsers have you tested in? chrome
- **Which framework are you using: react

**Comment by adamjmcgrath** [comment] 2020-09-22 10:43
Hi @adenta 

If you need to send custom parameters to the Authorization Server, add them to `loginOptions` directly. `appState` is used to store your application's state before doing the redirect (like a checkout basket id)

```js
const PrivateRoute = ({ component, ...args }) => (
  <Route
    component={withAuthenticationRequired(component, {
      onRedirecting: () => <Loading />,
      loginOptions: { foo: 'bar' },
      ...Auth0Options, // <= not sure what this is, but you probably don't need it
    })}
    {...args}
  />
);

export default PrivateRoute;
```

See the (confusingly named) "Indexible" section in https://auth0.github.io/auth0-react/interfaces/redirectloginoptions.html

**Comment by adenta** [comment] 2020-09-24 08:24
> If you need to send custom parameters to the Authorization Server, add them to loginOptions directly.
Unsure how to respond here. I am trying to send custom parameters to the Authorization Server. In the example I sent you I nested some custom params under `loginOptions.appState`. If you only need to nest parameters under `loginOptions` I  should _still_ see these params in my console when I log out the entire `config` object, no?

Anything I add to `loginOptions` is not being loaded into the `config` object on my universal login page, when using `withAuthenticationRequired`. This is not the case for the other method, `loginWithRedirect`.

**Comment by adamjmcgrath** [comment] 2020-09-25 09:16
Hey @adenta - I can't reproduce that issue myself. When I pass a custom option to login options in `withAuthenticationRequired` like:

```js
withAuthenticationRequired(component, {
  loginOptions: { foo: 'bar' },
});
```

I see, `&foo=bar` in the `/authorize` url as expected. Are you able to share some more code or the whole app? Could you also check the `/authorize` url in your network panel? Or do you have a running version of your app somewhere I can look at?

**Comment by adamjmcgrath** [comment] 2020-10-02 11:26
Hey @adenta - did you get a chance to look at https://github.com/auth0/auth0-react/issues/118#issuecomment-698820831 and are you still experiencing an issue? If so, can you share your application's code or a link to it running?

**Comment by adamjmcgrath** [comment] 2020-10-06 13:59
Hey @adenta - closing for now, feel free to reopen if you're still experiencing the issue

**Closed by adamjmcgrath** 2020-10-06 13:59 UTC
Labels: question

**Comment by adenta** [comment] 2020-10-06 14:01
I am still experiencing the issue, I will reopen when life calms down.
