### ISSUE TITLE
handleRedirectCallback fails on iOS (in Capacitor native app)

### ISSUE THREAD

**Issue by norbertschuler** [auth0/auth0-react#410] opened 2022-09-24 07:57 UTC
### Describe the problem

We want to build a native app wrapper with [Capacitor](https://capacitorjs.com/) around our Next.js website using this module. For authentication we want to open the Auth0 login dialog in the default browser of the device and after authentication redirect the user back into the native app. We tried this with deep links as well as with custom schemes to open our app again.

The problem we got is as following: Calling `handleRedirectCallback` with our callback url (containing a `code` and `state` value) is working on Android, but fails to work on iOS (16). (We can only assume it is because of how the Safari web view on iOS is treating security.)

### What was the expected behavior?

The `handleRedirectCallback` should also succeed and not fail on iOS with an event.url as e.g. `org.pftp.app://www1.plant-for-the-planet.org/login?code=***&state=***`

```typescript
        await handleRedirectCallback(event.url).then(() => {
           // do stuff here
        }).catch((error) => {
        });
```

### Reproduction

We use this in our [MR](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1559/files#r979191580) and it is always failing using e.g. the latest IOS 16 simulator using the latest version of this module with the following Auth0 application:
```
AUTH0_CUSTOM_DOMAIN=accounts.plant-for-the-planet.org
AUTH0_CLIENT_ID=6MME4DhfTZes2myvI0NXgWqGSIZdy0IH
```

### Environment

Modules used:
```
        "@auth0/auth0-react": "^1.11.0",
        "@capacitor/android": "^4.0.1",
        "@capacitor/app": "^4.0.1",
        "@capacitor/core": "^4.0.1",
        "@capacitor/ios": "^4.0.1",
        "next": "^11.1.4",
        "react": "^17.0.2",

```
Tested on:
- iOS 16 Simulator of iPhone 14

**Comment by aseprahman04** [comment] 2022-09-26 15:54
hi @norbertschuler  i faced the same issue, when the auth0 got redirect it return the code and state, but that method didn't get any result right sometimes got a timeout, when i tell to the BE guys and also tried directly using this https://auth0.com/docs/api/authentication#get-token this endpoint, the response from the api is 'grant request is invalid', i hope we can find any solution for this.

**Comment by aseprahman04** [comment] 2022-09-27 08:33
hi @norbertschuler  after some hours, i thought the problem caused by safari didn't send the code challenge for verifier code

**Comment by norbertschuler** [comment] 2022-09-28 18:20
> hi @norbertschuler after some hours, i thought the problem caused by safari didn't send the code challenge for verifier code

Thank you very much for taking your time investigating this. I am not sure if I understand your answer correctly. Does it mean, the problem can not be fixed due to Safari or are you still thinking about a possible solution?

**Comment by stevehobbsdev** [comment] 2022-09-29 13:50
@norbertschuler You mention a few times that it's failing, but how is it failing? Do you get an error, and if so what is it? Also, can you reproduce the error on iOS 15, or does it work fine on that version? Just trying to understand if it's a regression when using the latest OS.

Have you come across our [React sample](https://github.com/auth0-samples/auth0-ionic-samples/blob/main/react/src/App.tsx#L37-L50) where we handle this scenario, and is there anything there that would help you?

I'm going to close this issue as right now this is unlikely to be an issue with this SDK, but I'm happy to continue the conversation to figure out if we need to update our Ionic samples in some way.

**Closed by stevehobbsdev** 2022-09-29 13:50 UTC

**Comment by norbertschuler** [comment] 2022-09-29 13:56
> @norbertschuler You mention a few times that it's failing, but how is it failing? Do you get an error, and if so what is it? Also, can you reproduce the error on iOS 15, or does it work fine on that version? Just trying to understand if it's a regression when using the latest OS.

I'm sorry I wasn't precise enough. In the following code the `catch` always gets executed on iOS:

```typescript
        await handleRedirectCallback(event.url).then(() => {
           // do stuff here
        }).catch((error) => {
           console.log("iOS always show this part.")
        });

```
> Have you come across our [React sample](https://github.com/auth0-samples/auth0-ionic-samples/blob/main/react/src/App.tsx#L37-L50) where we handle this scenario, and is there anything there that would help you?

Thank you, I will test this sample as soon as possible.

**Comment by norbertschuler** [comment] 2022-09-29 16:14
I now compared the implementation of the sample app with my implementation. 

The sample app is using `buildAuthorizeUrl` and `buildLogoutUrl` together with the "@capacitor/browser" module.

... for login:
```typescript
  const login = async () => {
    const url = await buildAuthorizeUrl();
    await Browser.open({ url, windowName: "_self" });
  };
```
... and for logout:
```typescript
  const doLogout = async () => {
    await Browser.open({
      url: buildLogoutUrl({ returnTo: callbackUri }),
      windowName: "_self",
    });

    logout({ localOnly: true });
  };
```
This works well with `handleRedirectCallback` on iOS 16 or 15.

If I use this in my app it also works. 

But I am using `loginWithRedirect` and `logout` without "@capacitor/browser" and this does not work with `handleRedirectCallback`:

... for login:
```typescript
      loginWithRedirect({
        redirectUri: `${process.env.NEXTAUTH_URL}/login`,
        ui_locales: localStorage.getItem('language') || 'en',
      });
```
... and for logout:
```typescript
    logout({ returnTo: ${process.env.NEXTAUTH_URL} });
```

Now my question is: Do I have to live with the fact my implementation is not feasible for encapsulating the existing web application as an native iOS app (Android works) and do I have to refactor it using the first working solution or is there a bug to be fixed to also support my current implementation?

**Comment by stevehobbsdev** [comment] 2022-09-30 11:20
The reason we have `buildAuthorizeUrl` and `buildLogoutUrl` is for exactly this scenario, where you want to integrate with a Capacitor application (or some other framework that has its own native API for opening a browser.

`loginWithRedirect` and `logout` wrap those two methods respectively, but the problematic part is that they use `window.location.href` to do the browser redirection part, which causes default browser app on your device to open, as opposed to what you really want to do, which is use Capacitor's Browser plugin (which uses [`SFSafariViewController`](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller) on iOS and [Chrome Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/) on Android). This provides a better experience for users and feels much more native within your application.

**Comment by norbertschuler** [comment] 2022-10-01 10:48
Thank you for the support. We rebuild our application using buildAuthorizeUrl and buildLogoutUrl now.

**Comment by aseprahman04** [comment] 2022-10-03 12:08
hi @stevehobbsdev @norbertschuler  on IOS Simulator didn't get any issue, i just got an issue when do authorize using LINE, and LINE open the different safari. my temporary solution such like this 
`  useEffect(() => {
    CapApp.addListener("appUrlOpen", async ({ url }) => {
      if (url.startsWith(callbackUri)) {
        if (
          url.includes("state") &&
          (url.includes("code") || url.includes("error"))
        ) {
         
       try{
        const newurl = new URL(url);
const searchParams = newurl.searchParams;
        //const res = await handleRedirectCallback(url)
        const newRes = await axios.post(`${domain}/oauth/token`,{grant_type:'authorization_code', client_id: clientId, client_secret:'your_secrete', code:searchParams.get('code'),redirect_uri:callbackUri})
        console.log(newRes)
        // const res = await getAccessTokenSilently({'scope':'openid offline_access profile', audience:BASE_URL, detailedResponse: true, redirect_uri:callbackUri});
        if(newRes){
          const user = await axios.post(`${domain}/userinfo`,{}, {headers:{
            'Content-type':'application/x-www-form-urlencoded',
            'Accept':'application/x-www-form-urlencoded',
            'Authorization':`Bearer ${newRes.data.access_token}`
          }})
          if(user?.data){
            setUser(user.data)
            localStorage.setItem('profile', JSON.stringify(user.data))
          }
          await Browser.close();
          // doLogout()
        }
    
       } catch (err) {
        // await Browser.close();
        console.log(err)
       }
       
        }

        
      }
    });
  }, [handleRedirectCallback]);
`; because our auth0 using PKCE method, and doing some tricky on BE too. i do apologize if my language haven't enough for you guys
