### ISSUE TITLE
Unable to handle errors when POST call to /oauth/token fails, when the call is made by @auth0/auth0-react SDK

### ISSUE THREAD

**Issue by amitForta** [auth0/auth0-react#676] opened 2023-11-28 06:21 UTC
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am using [@auth0](https://community.auth0.com/u/auth0)/auth0-react SDK v2 in my React application, when I login and keep my keep a page in my application open for a long time and when refresh token expires (I have reduced refresh_token expiry time to 2 mins to simulate this issue in local), if I reload my page, I believe a POST call to /oauth/token endpoint is made by the SDK, since the refresh token has expired, the call fails with a 403 and I am unable to catch / handle this error. I am trying to avoid using the Iframe fallback method (useRefreshTokensFallback={true}).

Also when this fails, I was expecting that the error object exported by useAuth0 hook will contain some details about the failure, but its always set to undefined.

I am able handle the same error when I call getAccessTokenSilently explicitly from my code using a try catch block, the only challenge is when the call is made implicitly / by the SDK.

For more details with screenshot: https://community.auth0.com/t/unable-to-handle-errors-when-post-call-to-oauth-token-fails-when-the-call-is-made-by-auth0-auth0-react-sdk/121768

### Reproduction

Step 1: Setup auth0 in a React app, with @auth0/auth0-react SDK
Step 2: Keep refresh token expiry time to 2 mins
Step 3: Login and keep a page open for more than 2 mins so that the refresh token expires
Step 4: Reload the page

Since refresh token expires, POST call to /oauth/token fails and I am not able to catch and handle this error. Also the error object returned by useAuth0 hook is undefined.

### Additional context

https://community.auth0.com/t/unable-to-handle-errors-when-post-call-to-oauth-token-fails-when-the-call-is-made-by-auth0-auth0-react-sdk/121768

### auth0-react version

^2.2.1

### React version

^18.2.0

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment] 2023-11-28 08:25
Thanks for reaching out. It looks I can reproduce this, but I will need to do a bit more investigation here. Will get back to you as soon as possible

**Comment by amitForta** [comment] 2023-11-28 09:32
> Can you elaborate on the reasoning behind the fact that you want to avoid using the iframes fallback

Thank you @frederikprijck for a quick response.

My team raised a concern for using the iFrame fallback as in the migration document: https://github.com/auth0/auth0-spa-js/blob/main/MIGRATION_GUIDE.md#no-more-iframe-fallback-by-default-when-using-refresh-tokens, there is a mention that **This has caused problems before in environments that do not support iframes** and may be the reason auth0 team has decided to change the default value of useRefreshTokensFallback as false. Considering this we decided to handle token endpoint failures by ourself. Please let me know if I should add some more details. Thanks again.

**Comment by frederikprijck** [comment] 2023-11-28 09:34
Our iframes fallback does not work in situations that have third party cookies blocked, so we disable this by default.

However, using iframes is still the best solution for a lot of use-cases, including this. But you will need to mitigate the third party cookies issue by using custom domains.

So if you'd be using custom domains already, and the application shares the same domain as the IDP, it should work fine.

**Comment by frederikprijck** [comment] 2023-11-28 12:53
Additionally, can you elaborate a bit on why you'd want to be informed of the error at that particular time? It's by design that you are not informed in this case, but would love to learn about your use-case.

**Comment by amitForta** [comment] 2023-11-28 19:43
> Our iframes fallback does not work in situations that have third party cookies blocked, so we disable this by default.
> 
> However, using iframes is still the best solution for a lot of use-cases, including this. But you will need to mitigate the third party cookies issue by using custom domains.
> 
> So if you'd be using custom domains already, and the application shares the same domain as the IDP, it should work fine.

@frederikprijck we are using custom domains, so for us iFrames fallback will work fine for us. Thanks again for a quick response. Please suggest if I should close this issue or keep it open if you want to track something with it.

Regarding the error object, since I was not able to catch the request failure on page reload, I was kind of hoping that I would get some details from that error object and may be use it to redirect users to login page.

**Comment by frederikprijck** [comment] 2023-11-28 19:48
If you use the iframe fallback, you can use isAuthenticated being false to redirect to login page.

Closing as it looks like to be answered.

**Closed by frederikprijck** 2023-11-28 19:48 UTC
Labels: bug

**Comment by amitForta** [comment] 2023-11-29 05:13
> If you use the iframe fallback, you can use isAuthenticated being false to redirect to login page.
> 
> Closing as it looks like to be answered.

@frederikprijck my observation was when /token fails on load, some how isAuthenticated flag was set to true instead of false

**Comment by xtrinch** [comment] 2023-12-27 09:12
@frederikprijck That is my observation too. If /oauth/token returns 403 (Forbidden), isAuthenticated is set to true and error is null resulting in user getting stuck

**Comment by frederikprijck** [comment] 2023-12-27 09:18
@xtrinch do you mean the call to oauth/token using grant=refresh_token ?

**Comment by xtrinch** [comment] 2023-12-27 09:40
Right, thanks @frederikprijck , that worked. Tbh it's pretty odd that the default behaviour is technically buggy, should the default value not be useRefreshTokensFallback=true then? Or at least a big disclaimer in the docs this took me a good while to figure out

**Comment by frederikprijck** [comment] 2023-12-27 09:45
The default used to be what you say, useRefreshTokensFallback was true by default in V1, false in V2.

If u use refresh tokens, you are using the offline_access scope, meaning you want to disconnect from auth0, meaning we cant know whether the user is or isnt authenticated, unless you fallback to iframes. What will happen is, if refresh token fails, it will do a regular authorization code flow. If the user isnt authenticated, auth0 will tell us.

But once you use refresh tokens, without the fallback, you essentially are moving "offline", where offline means disconnected from the authentication state at auth0.

**Comment by xtrinch** [comment] 2023-12-27 11:18
@frederikprijck When you say custom domains solve this, what exactly do you mean by that? How would the naming scheme have to look like?

**Comment by frederikprijck** [comment] 2023-12-27 11:21
When i say custom domains, i refer to https://auth0.com/docs/customize/custom-domains.

Basically configuring auth0 with a custom domain, the same top level as your app, to avoid third-party cookies.
